themes/pytube-201601/templates/base.html

Add authors page link to nav bar

---

themes/pytube-201601/templates/author.html
themes/pytube-201601/templates/base.html

Rename Author(s) to Speaker(s) in templates

---

themes/pytube-201601/static/css/base.css
themes/pytube-201601/templates/article_media.html

Closes #25 
So far I've only tested it on iOS and in Chrome (Desktop with emulation). Fixed were video and image widths.

Improve mobile rendering

---

content/pages/errors/404.rst

As used on pyvideo.org's 404 page.

SWEET RAD ascii art

---

pelicanconf.py
themes/pytube-201601/templates/article_details.html
themes/pytube-201601/templates/base.html
themes/pytube-201601/templates/categories.html
themes/pytube-201601/templates/category.html

Rename categories to events

---

requirements-dev.txt
requirements.in
requirements.txt

move requirements to in file for pip-compile

move requirements to in file

---

themes/pytube-201601/templates/article.html

These tags allow social media sites to show previews of the content.
Fixes: #34

Add open graph meta tags

---

themes/pytube-201601/static/css/base.css
themes/pytube-201601/templates/index.html

* Some small CSS fixes
* Link to the talk's conference from the index "Latest talks" page

Small fixes

---

Makefile
bin/article_maker.py
bin/purge.py
pelicanconf.py
plugins/json_reader.py

This is the first part of supporting multiple video formats at once.
Additionally, it decreases the overall complexity of the rendering system, and should give us more ability to leverage all data present in the pyvideo-data json files when rendering.

Generate html pages directly from JSON files

---

themes/pytube-201601/templates/article_list_item_content.html

Added conference name to article_list_item

---

themes/pytube-201601/templates/base.html

This makes sure that for all relevant pages one of the tabs in the main
menu is marked as active.

Active a tab on every page

---

.gitmodules
README.rst

Update readme & submodules

---

plugins/json_reader.py

Updated json_reader to use the Pelican supplied ReST utilities rather than using docutils directly.
It will now also emit warnings for invalid ReST markup.

Update json_reader and report on invalid ReST markup

---

Makefile
README.rst

Introduce VERBOSE logging level

---

plugins/json_reader.py
themes/pytube-201601/templates/article_details.html
themes/pytube-201601/templates/article_media.html

Closes #113.
This also improves the video tab labels and adds an icon to each tab.

Lists all video URLs as "Media URL"

---

plugins/event_info.py

Skip processing .schema/category.json file

---

pelicanconf.py
plugins/aggregations.py
plugins/event_info.py
themes/pytube-201601/templates/index.html

Fix broken "latest events" links

---

themes/pytube-201601/templates/article.html

Add "Improve this page" link to video page

---

plugins/json_reader.py
themes/pytube-201601/templates/article.html

Fixes contribution link if category slug != path segment

---

plugins/json_reader.py
themes/pytube-201601/static/css/base.css
themes/pytube-201601/templates/article.html
themes/pytube-201601/templates/article_details.html

Add logic to show related URLs for each video

---

plugins/json_reader.py
themes/pytube-201601/static/js/thumb.js

This is needed for the DjangoCon Europe 2016 videos and should be merged before the respective PR in the data repository 😃

Add basic Wistia iframe support

---

themes/pytube-201601/static/css/base.css

* Make video description text justified
* Show 'discs' in lists in video description (but not in video details, except urls)

Css little enhancementes in video page

---

plugins/json_reader.py
themes/pytube-201601/templates/article_details.html

This way we can put labels on URLs to make them more descriptive. Related to https://github.com/pytube/data/pull/154

Support verbose related_urls
